spring:
    server:
        port: 8080
    application:
        name: TestVue
    datasource:
        url: jdbc:mysql://localhost:3306/test?serverTimezone=UTC&characterEncoding=utf8&allowPublicKeyRetrieval=true
        username: admin
        password: 123456
        driver-class-name: com.mysql.cj.jdbc.Driver
mybatis-plus:
    mapper-locations: classpath*:mappers/*Mapper.xml
    type-aliases-package: com.example.testvue.entity  # 你的实体类包路径